//IMMEDIATELY INVOKED FUNCTION EXPRESSION-USED FOR CODE WHICH HAS TO IMMEDIATELY RUN AFTER START
(function() {
    console.log("I run immediately!");
})();

//()()--HAVE TO USE LIKE THIS 
//HAVE TO USE SEMICOLON AFTER IIFE
